#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("gladostwenty.droid.Resource", IsApplication=true)]

namespace gladostwenty.droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Gcm.Client.Resource.String.library_name = global::gladostwenty.droid.Resource.String.library_name;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::gladostwenty.droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::gladostwenty.droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::gladostwenty.droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::gladostwenty.droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::gladostwenty.droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::gladostwenty.droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::gladostwenty.droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::gladostwenty.droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::gladostwenty.droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::gladostwenty.droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::gladostwenty.droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::gladostwenty.droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::gladostwenty.droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::gladostwenty.droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::gladostwenty.droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::gladostwenty.droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::gladostwenty.droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::gladostwenty.droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::gladostwenty.droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::gladostwenty.droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::gladostwenty.droid.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080000
			public const int busy_reason_list = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int number_array = 2131230721;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070003
			public const int accent = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int main_color = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int main_color_dark = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int main_color_light = 2131165186;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_launcher = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int RoundedTextBox = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int splash = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int splashscreen = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int splashscreenglados = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int telstralogo = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MvvmCrossTagId = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MvxBindingTagUnique = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int btnDone = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int btnRequest = 2131034122;
			
			// aapt resource value: 0x7f050018
			public const int btnSend = 2131034136;
			
			// aapt resource value: 0x7f050009
			public const int fldContactNumber = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int fldEmail = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int fldFirstName = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int fldLastName = 2131034117;
			
			// aapt resource value: 0x7f05000d
			public const int imageView1 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int label = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int label2 = 2131034127;
			
			// aapt resource value: 0x7f050017
			public const int lblAttachLocation = 2131034135;
			
			// aapt resource value: 0x7f050013
			public const int lblAvailableIn = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int lblAvailableInPicker = 2131034132;
			
			// aapt resource value: 0x7f050010
			public const int lblBusy = 2131034128;
			
			// aapt resource value: 0x7f050008
			public const int lblContactNumber = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int lblEmail = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int lblFirstName = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int lblLastName = 2131034116;
			
			// aapt resource value: 0x7f050015
			public const int lblNote = 2131034133;
			
			// aapt resource value: 0x7f050011
			public const int lblReason = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int lblReasonPicker = 2131034130;
			
			// aapt resource value: 0x7f05000c
			public const int progressBar1 = 2131034124;
			
			// aapt resource value: 0x7f05001b
			public const int snrBusy = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int snrNumberBusy = 2131034140;
			
			// aapt resource value: 0x7f050019
			public const int swtAttachLocation = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int swtBusy = 2131034138;
			
			// aapt resource value: 0x7f050016
			public const int txtNotes = 2131034134;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ContactDetailView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FirstView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LoginView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int OnRequest = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int RequestStatusView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SplashScreen = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int StatusItemLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int StatusListView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int UserItemLayout = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int ApplicationName = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int Hello = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int busy_default = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int library_name = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int number_default = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int ApplicationTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int LoginViewTheme = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Theme_Splash = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
